In [1]:
pip install nltk==3.5.0

     |████████████████████████████████| 1.4 MB 4.2 MB/s eta 0:00:01
     |████████████████████████████████| 82 kB 951 kB/s  eta 0:00:01
     |████████████████████████████████| 661 kB 16.4 MB/s eta 0:00:01
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434678 sha256=ef290002fa6899d6530f5e8e96f8ae10a19d123e5b8a71b3f46b49a088885e18
  Stored in directory: /home/jovyan/.cache/pip/wheels/45/6c/46/a1865e7ba706b3817f5d1b2ff7ce8996aabdd0d03d47ba0266
Successfully built nltk
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install gensim

     |████████████████████████████████| 24.2 MB 4.5 MB/s eta 0:00:01    |████████▏                       | 6.2 MB 4.5 MB/s eta 0:00:05
     |████████████████████████████████| 116 kB 22.3 MB/s eta 0:00:01
     |████████████████████████████████| 1.4 MB 28.8 MB/s eta 0:00:01
     |████████████████████████████████| 128 kB 27.2 MB/s eta 0:00:01
     |████████████████████████████████| 69 kB 11.2 MB/s eta 0:00:01
     |████████████████████████████████| 6.3 MB 30.8 MB/s eta 0:00:01
     |████████████████████████████████| 547 kB 30.3 MB/s eta 0:00:01
  Created wheel for smart-open: filename=smart_open-2.1.0-py3-none-any.whl size=110317 sha256=e3988d0cffa61b68b6daca35cc3125b78bbd4673c584113911f736d8a69e7a1b
  Stored in directory: /home/jovyan/.cache/pip/wheels/56/b5/6d/86dbe4f29d4688e5163a8b8c6b740494310040286fca4dc648
Successfully built smart-open
Note: you may need to restart the kernel to use updated packages.


In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:80% !important;}</style>"))

In [4]:
raw_txt = """Welcome to the world of Deep Learning for NLP! We're in this together, and we'll learn together. 
NLP is amazing, and Deep Learning makes it even more fun. Let's learn!"""

### Tokenization

In [5]:
import nltk
nltk.download('punkt')
from nltk import tokenize

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [6]:
tokenize.sent_tokenize(raw_txt)

['Welcome to the world of Deep Learning for NLP!',
 "We're in this together, and we'll learn together.",
 'NLP is amazing, and Deep Learning makes it even more fun.',
 "Let's learn!"]

In [7]:
txt_sents = tokenize.sent_tokenize(raw_txt)

In [8]:
type(txt_sents), len(txt_sents)

(list, 4)

In [9]:
txt_words = [tokenize.word_tokenize(sent) for sent in txt_sents]
type(txt_words), type(txt_words[0])

(list, list)

In [10]:
print(txt_words[:2])

[['Welcome', 'to', 'the', 'world', 'of', 'Deep', 'Learning', 'for', 'NLP', '!'], ['We', "'re", 'in', 'this', 'together', ',', 'and', 'we', "'ll", 'learn', 'together', '.']]


### Normalizing case

In [11]:
#You needn't run this
raw_txt = raw_txt.lower()

In [12]:
txt_sents = [sent.lower() for sent in txt_sents]
txt_sents

['welcome to the world of deep learning for nlp!',
 "we're in this together, and we'll learn together.",
 'nlp is amazing, and deep learning makes it even more fun.',
 "let's learn!"]

In [13]:
txt_words = [tokenize.word_tokenize(sent) for sent in txt_sents]

In [14]:
print(txt_words[:2])

[['welcome', 'to', 'the', 'world', 'of', 'deep', 'learning', 'for', 'nlp', '!'], ['we', "'re", 'in', 'this', 'together', ',', 'and', 'we', "'ll", 'learn', 'together', '.']]


### Removing punctuation

In [15]:
from string import punctuation

In [16]:
list_punct = list(punctuation)
print(list_punct)

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']


In [17]:
def drop_punct(input_tokens):
    return [token for token in input_tokens if token not in list_punct]

In [18]:
drop_punct(["let",".","us",".","go","!"])

['let', 'us', 'go']

In [19]:
txt_words_nopunct = [drop_punct(sent) for sent in txt_words]
print(txt_words_nopunct)

[['welcome', 'to', 'the', 'world', 'of', 'deep', 'learning', 'for', 'nlp'], ['we', "'re", 'in', 'this', 'together', 'and', 'we', "'ll", 'learn', 'together'], ['nlp', 'is', 'amazing', 'and', 'deep', 'learning', 'makes', 'it', 'even', 'more', 'fun'], ['let', "'s", 'learn']]


#### Removing stop words

In [20]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [21]:
from nltk.corpus import stopwords
list_stop = stopwords.words("english")
len(list_stop)

179

In [22]:
print(list_stop[:50])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be']


### Exercise 4.01: Tokenizing, Case Normalization, Punctuation and Stop Word Removal

In [23]:
import nltk
from nltk import tokenize

In [24]:
raw_txt = """Welcome to the world of Deep Learning for NLP! We're in this together, and we'll learn together. NLP is amazing, and Deep Learning makes it even more fun. Let's learn!"""

In [25]:
txt_sents = tokenize.sent_tokenize(raw_txt.lower())
txt_words = [tokenize.word_tokenize(sent) for sent in txt_sents]

from string import punctuation
stop_punct = list(punctuation)

from nltk.corpus import stopwords
stop_nltk = stopwords.words("english")

stop_final = stop_punct + stop_nltk

In [26]:
def drop_stop(input_tokens):
    return [token for token in input_tokens if token not in stop_final]

In [27]:
txt_words_nostop = [drop_stop(sent) for sent in txt_words]

In [28]:
print(txt_words_nostop[0])

['welcome', 'world', 'deep', 'learning', 'nlp']


### Stemming

In [29]:
from nltk.stem import PorterStemmer

In [30]:
stemmer_p = PorterStemmer()

In [31]:
print(stemmer_p.stem("driving"))

drive


In [32]:
txt = "I mustered all my drive, drove to the driving school!"

In [33]:
tokens = tokenize.word_tokenize(txt)
print([stemmer_p.stem(word) for word in tokens])

['I', 'muster', 'all', 'my', 'drive', ',', 'drove', 'to', 'the', 'drive', 'school', '!']


### Lemmatization

In [34]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [35]:
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()

In [36]:
lemmatizer.lemmatize("ponies")

'pony'

### Exercise 4.02: Stemming Our Data

In [37]:
from nltk.stem import PorterStemmer

In [38]:
stemmer_p = PorterStemmer()

In [39]:
print([stemmer_p.stem(token) for token in txt_words_nostop[0]])

['welcom', 'world', 'deep', 'learn', 'nlp']


Applying stemmer to all the sentences

In [40]:
txt_words_stem = [[stemmer_p.stem(token) for token in sent] for sent in txt_words_nostop]

In [41]:
txt_words_stem

[['welcom', 'world', 'deep', 'learn', 'nlp'],
 ["'re", 'togeth', "'ll", 'learn', 'togeth'],
 ['nlp', 'amaz', 'deep', 'learn', 'make', 'even', 'fun'],
 ['let', "'s", 'learn']]

### Downloading Text Corpora using NLTK

In [42]:
import nltk
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


True

In [43]:
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [44]:
alice_raw = nltk.corpus.gutenberg.raw('carroll-alice.txt')

In [45]:
alice_raw[:800]

"[Alice's Adventures in Wonderland by Lewis Carroll 1865]\n\nCHAPTER I. Down the Rabbit-Hole\n\nAlice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, 'and what is the use of a book,' thought Alice 'without pictures or\nconversation?'\n\nSo she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a White Rabbit with pink eyes ran\nclose by her.\n\nThere was nothing so VERY remarkable in that; nor did Alice think it so\nVERY much out of the way to hear the Rabbit"

## Representation
### 1. One hot encoding

In [46]:
txt_words_nostop

[['welcome', 'world', 'deep', 'learning', 'nlp'],
 ["'re", 'together', "'ll", 'learn', 'together'],
 ['nlp', 'amazing', 'deep', 'learning', 'makes', 'even', 'fun'],
 ['let', "'s", 'learn']]

### Exercise 4.03: Creating One-Hot Encoding for Our Data

In [47]:
print(txt_words_nostop)

[['welcome', 'world', 'deep', 'learning', 'nlp'], ["'re", 'together', "'ll", 'learn', 'together'], ['nlp', 'amazing', 'deep', 'learning', 'makes', 'even', 'fun'], ['let', "'s", 'learn']]


In [48]:
target_terms = ["nlp","deep","learn"]

In [49]:
def get_onehot(sent):
    return [1 if term in  sent else 0 for term in target_terms]

In [50]:
one_hot_mat = [get_onehot(sent) for sent in txt_words_nostop]

In [51]:
import numpy as np

In [52]:
np.array(one_hot_mat)

array([[1, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [0, 0, 1]])

### Term Frequencies

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
vectorizer = CountVectorizer(max_features = 5)

In [55]:
vectorizer.fit(txt_sents)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=5, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [56]:
vectorizer.vocabulary_

{'deep': 1, 'we': 4, 'together': 3, 'and': 0, 'learn': 2}

In [57]:
txt_dtm = vectorizer.fit_transform(txt_sents)

In [58]:
txt_dtm.toarray()

array([[0, 1, 0, 0, 0],
       [1, 0, 1, 2, 2],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [59]:
txt_sents

['welcome to the world of deep learning for nlp!',
 "we're in this together, and we'll learn together.",
 'nlp is amazing, and deep learning makes it even more fun.',
 "let's learn!"]

In [60]:
def do_nothing(doc):
    return doc

In [61]:
vectorizer = CountVectorizer(max_features=5, 
                             preprocessor=do_nothing, 
                             tokenizer=do_nothing)

In [62]:
txt_dtm = vectorizer.fit_transform(txt_words_stem)

In [63]:
txt_dtm.toarray()

array([[0, 1, 1, 1, 0],
       [1, 0, 1, 0, 2],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0]])

In [64]:
vectorizer.vocabulary_

{'deep': 1, 'learn': 2, 'nlp': 3, 'togeth': 4, "'ll": 0}

In [65]:
txt_words_stem

[['welcom', 'world', 'deep', 'learn', 'nlp'],
 ["'re", 'togeth', "'ll", 'learn', 'togeth'],
 ['nlp', 'amaz', 'deep', 'learn', 'make', 'even', 'fun'],
 ['let', "'s", 'learn']]

### Exercise 4.04: Document Term Matrix with TF-IDF

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
vectorizer_tfidf = TfidfVectorizer(max_features=5)

In [68]:
vectorizer_tfidf.fit(txt_sents)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=5,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [69]:
vectorizer_tfidf.vocabulary_

{'deep': 1, 'we': 4, 'together': 3, 'and': 0, 'learn': 2}

In [70]:
txt_tfidf = vectorizer_tfidf.transform(txt_sents)

In [71]:
txt_tfidf.toarray()

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.25932364, 0.        , 0.25932364, 0.65783832, 0.65783832],
       [0.70710678, 0.70710678, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ]])

In [72]:
vectorizer_tfidf.idf_

array([1.51082562, 1.51082562, 1.51082562, 1.91629073, 1.91629073])

## Training Our Own Embeddings

In [73]:
import gensim.downloader as api
from gensim.models import word2vec

In [74]:
#Another way of loading the data. if this doesn't work, you could use the text8 corpus local file
dataset = api.load("text8")

[==================================================] 100.0% 31.6/31.6MB downloaded


To ensure reproducible results, set random seed as 1

In [75]:
np.random.seed(1)

In [76]:
dataset = word2vec.Text8Corpus("text8")

In [77]:
model = word2vec.Word2Vec(dataset)

In [78]:
print(model.wv["animal"])

[-8.5838413e-01  1.4214208e+00  4.6447900e-01  7.0885710e-02
  1.6896889e-01 -9.8778456e-02  1.1402733e+00 -2.9789758e+00
  2.8246179e-01 -8.7568551e-02 -1.2357916e+00 -1.2885849e-01
  1.2703731e+00 -1.4592729e-02 -3.8777024e-01  2.9091379e-01
  9.5472641e-02  1.4563963e-01 -6.8076456e-01 -9.9715537e-01
  1.4350164e+00  2.1312969e+00  1.9116565e-03  1.0840468e+00
  7.8456789e-01  1.2306607e+00 -4.5679808e-01 -2.3956151e+00
  4.6197531e-01  2.9375532e-01 -4.0576980e-01  2.0033605e+00
 -1.4525657e+00 -4.6804035e-01 -9.8208651e-02  8.8128763e-01
  9.9858916e-01  2.4697350e-01  1.6031005e+00 -1.2744416e+00
  7.7264303e-01 -1.7759993e+00 -3.0845227e+00 -1.5518727e+00
 -6.5049249e-01  7.8414708e-01 -1.0474778e+00  3.9749783e-01
 -2.6754682e+00 -4.4862261e-01 -1.3782256e+00  1.5887188e+00
  1.4766140e+00  4.3363068e-01 -2.2527428e-01 -2.4994092e-01
  1.0335336e+00 -5.8475828e-01 -1.4084058e+00  8.6268568e-01
 -1.6042060e+00  1.5416752e+00 -2.1892607e+00 -2.9363409e-01
 -1.3044649e+00 -1.33466

In [79]:
len(model.wv["animal"])

100

In [80]:
model.wv.most_similar("animal")

[('insect', 0.7552701830863953),
 ('animals', 0.7310898303985596),
 ('feces', 0.6877481937408447),
 ('aquatic', 0.6783003807067871),
 ('sentient', 0.6687874794006348),
 ('mammal', 0.6686221361160278),
 ('insects', 0.6608380675315857),
 ('eating', 0.6508541107177734),
 ('humans', 0.6505103707313538),
 ('ants', 0.6468088626861572)]

In [81]:
model.wv.most_similar("happiness")

[('goodness', 0.7682030200958252),
 ('compassion', 0.7660053968429565),
 ('humanity', 0.7659634351730347),
 ('perfection', 0.746347963809967),
 ('pleasure', 0.7299338579177856),
 ('mankind', 0.7249332666397095),
 ('desires', 0.7136735916137695),
 ('conscious', 0.7103390693664551),
 ('immortality', 0.7067128419876099),
 ('dignity', 0.7043787837028503)]

### Semantic Regularities in Word Embeddings

In [82]:
model.wv.most_similar(positive=['woman', 'king'], negative=['man'], topn=5)

[('queen', 0.6854889392852783),
 ('elizabeth', 0.6392526030540466),
 ('prince', 0.6301933526992798),
 ('empress', 0.6284343004226685),
 ('princess', 0.6062546968460083)]

In [83]:
model.wv.most_similar(positive=['uncle', 'woman'], negative=['man'], topn=5)

[('aunt', 0.8330071568489075),
 ('grandmother', 0.8115813732147217),
 ('wife', 0.8074036240577698),
 ('niece', 0.8025387525558472),
 ('edith', 0.7721768617630005)]

### Exercise 4.05: Vectors for Phrases

In [84]:
v1 = model.wv['get']
v2 = model.wv['happy']
res1 = (v1+v2)/2

In [85]:
v1 = model.wv['make']
v2 = model.wv['merry']
res2 = (v1+v2)/2

In [86]:
model.wv.cosine_similarities(res1, [res2])

array([0.5505672], dtype=float32)

### Effect of Parameters - 'size' of the Vector

In [87]:
model = word2vec.Word2Vec(dataset, size=30)

In [88]:
model.wv.most_similar(positive=['woman', 'king'], negative=['man'], topn=5)

[('empress', 0.8615267276763916),
 ('emperor', 0.8606838583946228),
 ('prince', 0.8221743106842041),
 ('regent', 0.820101261138916),
 ('son', 0.8148695826530457)]

### Effect of parameters - skipgram vs. CBOW

#### Rare terms - oeuvre

In [89]:
model = word2vec.Word2Vec(dataset)

In [90]:
model.wv.most_similar("oeuvre", topn=5)

[('surrealist', 0.7391599416732788),
 ('orchestration', 0.7302736043930054),
 ('lithographs', 0.720194935798645),
 ('sonnet', 0.7199317216873169),
 ('nieve', 0.7163490056991577)]

In [91]:
model_sg = word2vec.Word2Vec(dataset, sg=1)

In [92]:
model_sg.wv.most_similar("oeuvre", topn=5)

[('masterful', 0.8615211248397827),
 ('lithographs', 0.8272578120231628),
 ('impressionistic', 0.821493923664093),
 ('prolifically', 0.8097631931304932),
 ('speght', 0.8088525533676147)]

### Exercise 4.06: Training Word Vectors on Different Datasets

In [93]:
nltk.download('brown')
nltk.download('movie_reviews')

[nltk_data] Downloading package brown to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package movie_reviews to
[nltk_data]     /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.


True

In [94]:
from nltk.corpus import brown, movie_reviews

In [95]:
model_brown = word2vec.Word2Vec(brown.sents(), sg=1)
model_movie = word2vec.Word2Vec(movie_reviews.sents(), sg=1)

In [96]:
model_brown.wv.most_similar('money', topn=5)

[('care', 0.8496509194374084),
 ('friendship', 0.844196081161499),
 ('job', 0.8403249979019165),
 ('permission', 0.8254338502883911),
 ('anywhere', 0.824324369430542)]

In [97]:
model_movie.wv.most_similar('money', topn=5)

[('cash', 0.7355437278747559),
 ('record', 0.7169833183288574),
 ('ransom', 0.6896260976791382),
 ('bucks', 0.6831791400909424),
 ('pact', 0.6827759146690369)]

### Using Pre-Trained Word Vectors

### Activity 4.01: Text Preprocessing of the 'Alice in Wonderland' Text

In [98]:
alice_raw[:800]

"[Alice's Adventures in Wonderland by Lewis Carroll 1865]\n\nCHAPTER I. Down the Rabbit-Hole\n\nAlice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, 'and what is the use of a book,' thought Alice 'without pictures or\nconversation?'\n\nSo she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a White Rabbit with pink eyes ran\nclose by her.\n\nThere was nothing so VERY remarkable in that; nor did Alice think it so\nVERY much out of the way to hear the Rabbit"

#### Solution

In [99]:
txt_sents = tokenize.sent_tokenize(alice_raw.lower())

In [100]:
txt_words = [tokenize.word_tokenize(sent) for sent in txt_sents]

In [101]:
from string import punctuation
stop_punct = list(punctuation)

from nltk.corpus import stopwords
stop_nltk = stopwords.words("english")

In [102]:
stop_context = ["--", "said"]

In [103]:
stop_final = stop_punct + stop_nltk + stop_context

In [104]:
def drop_stop(input_tokens):
    return [token for token in input_tokens if token not in stop_final]

In [105]:
alice_words_nostop = [drop_stop(sent) for sent in txt_words]
print(alice_words_nostop[:2])

[['alice', "'s", 'adventures', 'wonderland', 'lewis', 'carroll', '1865', 'chapter', 'i.', 'rabbit-hole', 'alice', 'beginning', 'get', 'tired', 'sitting', 'sister', 'bank', 'nothing', 'twice', 'peeped', 'book', 'sister', 'reading', 'pictures', 'conversations', "'and", 'use', 'book', 'thought', 'alice', "'without", 'pictures', 'conversation'], ['considering', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisy-chain', 'would', 'worth', 'trouble', 'getting', 'picking', 'daisies', 'suddenly', 'white', 'rabbit', 'pink', 'eyes', 'ran', 'close']]


In [106]:
from nltk.stem import PorterStemmer
stemmer_p = PorterStemmer()

In [107]:
alice_words_stem = [[stemmer_p.stem(token) for token in sent] for sent in alice_words_nostop]

In [108]:
print(alice_words_stem[:5])

[['alic', "'s", 'adventur', 'wonderland', 'lewi', 'carrol', '1865', 'chapter', 'i.', 'rabbit-hol', 'alic', 'begin', 'get', 'tire', 'sit', 'sister', 'bank', 'noth', 'twice', 'peep', 'book', 'sister', 'read', 'pictur', 'convers', "'and", 'use', 'book', 'thought', 'alic', "'without", 'pictur', 'convers'], ['consid', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepi', 'stupid', 'whether', 'pleasur', 'make', 'daisy-chain', 'would', 'worth', 'troubl', 'get', 'pick', 'daisi', 'suddenli', 'white', 'rabbit', 'pink', 'eye', 'ran', 'close'], ['noth', 'remark', 'alic', 'think', 'much', 'way', 'hear', 'rabbit', 'say', "'oh", 'dear'], ['oh', 'dear'], ['shall', 'late']]
