In [34]:
import tensorflow as tf
from sklearn.metrics import accuracy_score

In [35]:
x=[[0.,0.],[0.,1.],[1.,0.],[1.,1.]]
y=[[0.],[1.],[1.],[1.]]

In [36]:
Number_of_features=2
Number_of_units=1  

In [37]:
# weights and bias
weight=tf.Variable(tf.zeros([Number_of_features,Number_of_units]),tf.float32)  
bias=tf.Variable(tf.zeros([Number_of_units]),tf.float32)

In [38]:
def perceptron(x):
    I=tf.add(tf.matmul(x,weight),bias)
    output=tf.sigmoid(I)
    return output


In [39]:
optimizer=tf.optimizers.Adam(.01)

In [40]:
def train(i):
    for n in range(i):
        loss=lambda: abs(tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y,logits=perceptron(x))))
        optimizer.minimize(loss,[weight,bias])

In [41]:
train(1000)     

In [42]:
tf.print(weight)

[[5.33743715]
 [5.33743715]]


In [43]:
tf.print(bias)

[-2.56196594]


In [44]:
result=perceptron(x)

In [45]:
tf.print(result)

[[0.0716266632]
 [0.941335917]
 [0.941335917]
 [0.999700427]]


In [46]:
ypred=tf.round(result)

In [47]:
tf.print(ypred)

[[0]
 [1]
 [1]
 [1]]


In [48]:
accuracy_score(y, ypred)

1.0

In [49]:
# The end 