# Multiclass


## Import TensorFlow and other libraries

In [1]:
import tensorflow as tf
import pandas as pd

from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt
%matplotlib inline

from pandas import get_dummies

In [2]:
mnist = tf.keras.datasets.mnist

(train_features,train_labels), (test_features,test_labels) = mnist.load_data()
train_features, test_features = train_features / 255.0, test_features / 255.0

In [3]:
#read the data 

In [4]:
#prepare the training data

In [5]:
x=tf.reshape(train_features,[60000,784])

In [6]:
x=tf.Variable(x)
x=tf.cast(x,tf.float32)

In [7]:
y_hot = get_dummies(train_labels)

In [8]:
y=y_hot.values

In [9]:
#perceptron training 

In [10]:
#defining the parameters

In [11]:
Number_of_features=784
Number_of_units=10  

In [12]:
# weights and bias
weight=tf.Variable(tf.zeros([Number_of_features,Number_of_units]))  
bias=tf.Variable(tf.zeros([Number_of_units]))

In [13]:
#perceptron definition
def perceptron(x):
    I=tf.add(tf.matmul(x,weight),bias)
    output=tf.nn.softmax(I)
    return output

In [14]:
#optimizer
optimizer=tf.optimizers.Adam(.01)

In [15]:
#training definition
def train(i):
    for n in range(i):
        loss=lambda: abs(tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y,logits=perceptron(x))))
        optimizer.minimize(loss,[weight,bias])

In [16]:
#Train the network
train(100)

In [17]:
tf.print(weight)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
#prepare the test data to measure the accuracy

In [19]:
test=tf.reshape(test_features,[10000,784])
 
test=tf.Variable(test)
test=tf.cast(test,tf.float32)
 
test_hot = get_dummies(test_labels)
test_matrix=test_hot.values


In [20]:
ypred=perceptron(test)

In [21]:
ypred=tf.round(ypred)

In [22]:
accuracy_score(test_hot, ypred)

0.9099

In [23]:
###The End