In [1]:
import tensorflow as tf

In [11]:
X = tf.Variable([[0.,0.],[0.,1.],[1.,0.],[1.,1.]], tf.float32)  # 4x2, input data table of OR
y = tf.Variable([0.0, 1.0, 1.0, 1.0], tf.float32) # OR truth table labels
y = tf.reshape(y, [4, 1])  # convert to 4x1

NUM_FEATURES = X.shape[1]
OUTPUT_SIZE = 1

W = tf.Variable(tf.zeros([NUM_FEATURES, 1]), tf.float32)
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), tf.float32)

def perceptron(X):
    z = tf.add(tf.matmul(X, W), B)
    output = tf.sigmoid(z)
    return output

In [12]:
print(perceptron(X))

tf.Tensor(
[[0.5]
 [0.5]
 [0.5]
 [0.5]], shape=(4, 1), dtype=float32)


In [27]:
learning_rate=0.01

optimizer = tf.optimizers.SGD(learning_rate)

In [28]:
no_of_epochs = 1000

for n in range(no_of_epochs):
    loss = lambda: abs(tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=perceptron(X))))
    optimizer.minimize(loss, [W, B])


In [29]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[6.7163224],
       [6.7163224]], dtype=float32)>


In [30]:
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-3.1965985]], dtype=float32)>


In [31]:
predictions = perceptron(X)
print(predictions)

tf.Tensor(
[[0.03929393]
 [0.97124374]
 [0.97124374]
 [0.9999641 ]], shape=(4, 1), dtype=float32)


In [32]:
ypred = tf.round(predictions)
print(ypred)

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [1.]], shape=(4, 1), dtype=float32)


In [33]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y, ypred))

1.0
