In [30]:
import tensorflow as tf
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])

In [31]:
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [32]:
X.shape

TensorShape([3, 3])

In [33]:
tf.print(tf.argmax(X,axis=0))

[0 1 2]


In [34]:
tf.print(tf.argmax(X,axis=1))

[0 1 0]
