# Code to explain Reshape 

In [1]:
import tensorflow as tf

In [2]:
x=tf.Variable([2,50,3,10,4,5,6,7])

In [3]:
y=tf.Variable([[1,2],[3,4],[5,6]])

In [4]:
z=tf.Variable([[1,9],[8,2],[8,7]])

In [5]:
tf.print(x)

[2 50 3 ... 5 6 7]


In [6]:
x.shape

TensorShape([8])

In [7]:
tf.print(y)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
y.shape

TensorShape([3, 2])

# Reshape

In [9]:
tf.print(tf.reshape(y,[2,3]))

[[1 2 3]
 [4 5 6]]


In [10]:
tf.print(z)

[[1 9]
 [8 2]
 [8 7]]


In [11]:
z.shape

TensorShape([3, 2])

In [12]:
tf.print(tf.reshape(z,[2,3]))


[[1 9 8]
 [2 8 7]]


In [13]:
tf.print(tf.reshape(z,[1,6]))


[[1 9 8 2 8 7]]


In [14]:
tf.print(tf.reshape(z,[6,1]))


[[1]
 [9]
 [8]
 [2]
 [8]
 [7]]


In [15]:
tf.print(tf.reshape(z,[1,2,3]))

[[[1 9 8]
  [2 8 7]]]


In [25]:
tf.print(z)

[[1 9]
 [8 2]
 [8 7]]


In [26]:
z=tf.reshape(z,[1,2,3])

In [27]:
tf.print(z)

[[[1 9 8]
  [2 8 7]]]


In [ ]:
#Important to note...it only gives the location or index of the max value

In [ ]:
#this will be used later in Neural Network classification