# Code to explain argmax

In [1]:
import tensorflow as tf

In [2]:
x=tf.Variable([2,50,3,10,4,5,6,7])

In [3]:
y=tf.Variable([[1,2],[3,4],[5,6]])

In [4]:
z=tf.Variable([[1,9],[8,2],[8,7]])

In [5]:
tf.print(x)

[2 50 3 ... 5 6 7]


In [6]:
x.shape

TensorShape([8])

In [7]:
tf.print(y)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
y.shape

TensorShape([3, 2])

# Max value

In [19]:
tf.print(tf.argmax(x,axis=0))

1


In [20]:
tf.print(z)

[[1 9]
 [8 2]
 [8 7]]


In [21]:
tf.print(tf.argmax(z,axis=0))

[1 0]


In [24]:
tf.print(tf.argmax(z,axis=1))

[1 0 0]


In [ ]:
#Important to note...it only gives the location or index of the max value

In [ ]:
#this will be used later in Neural Network classification