In [6]:
import tensorflow as tf
A=tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])

In [7]:
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [8]:
A.shape

TensorShape([5, 4])

In [9]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [10]:
A.shape

TensorShape([5, 4])

In [11]:
A = tf.reshape(A,[5,4,1])

In [12]:
A.shape

TensorShape([5, 4, 1])

In [14]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]
